# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# admin user
User.create( email: ENV['MAIL_ADDRESS'], password: ENV['MAIL_ACCOUNT_PASSWORD'], admin: true )
User.create( email: ENV['GUEST_ADDRESS'], password: ENV['GUEST_PASSWORD'], admin: false )

# Makers
Maker.create( id: 1, maker_name: 'クレオス')
Maker.create( id: 2, maker_name: 'ガイアノーツ')
Maker.create( id: 3, maker_name: 'タミヤ')

#Creos Colors 
# Mr.カラー
Color.create( color_name: 'ホワイト', color_code: 'FFFFFF', maker_id: '1', color_number: 'C1' )
Color.create( color_name: 'ブラック', color_code: '231815', maker_id: '1', color_number: 'C2' )
Color.create( color_name: 'レッド', color_code: 'E60012', maker_id: '1', color_number: 'C3' )
Color.create( color_name: 'イエロー', color_code: 'FFE100', maker_id: '1', color_number: 'C4' )
Color.create( color_name: 'ブルー', color_code: '0054A7', maker_id: '1', color_number: 'C5' )
Color.create( color_name: 'グリーン', color_code: '006830', maker_id: '1', color_number: 'C6' )
Color.create( color_name: 'ブラウン', color_code: 'CA3929', maker_id: '1', color_number: 'C7' )
Color.create( color_name: 'シルバー', color_code: 'DCDDDD', maker_id: '1', color_number: 'C8' )
Color.create( color_name: 'ゴールド', color_code: 'DFB603', maker_id: '1', color_number: 'C9' )
Color.create( color_name: 'カッパー', color_code: 'CE722A', maker_id: '1', color_number: 'C10' )
Color.create( color_name: 'ガルグレー', color_code: 'BDC3C4', maker_id: '1', color_number: 'C11' )
Color.create( color_name: 'オリーブドラブ', color_code: '685932', maker_id: '1', color_number: 'C12' )
Color.create( color_name: 'ニュートラルグレー', color_code: '75858D', maker_id: '1', color_number: 'C13' )
Color.create( color_name: 'ネービーブルー', color_code: '004652', maker_id: '1', color_number: 'C14' )
Color.create( color_name: '暗緑色(中島系)', color_code: '00381F', maker_id: '1', color_number: 'C15' )
Color.create( color_name: '濃緑色', color_code: '004D39', maker_id: '1', color_number: 'C16' )
Color.create( color_name: 'RLM71ダークグリーン', color_code: '595A4E', maker_id: '1', color_number: 'C17' )
Color.create( color_name: 'RLM70ブラックグリーン', color_code: '213C50', maker_id: '1', color_number: 'C18' )
Color.create( color_name: 'サンディブラウン', color_code: '9F8237', maker_id: '1', color_number: 'C19' )
Color.create( color_name: 'ライトブルー', color_code: '48BAA0', maker_id: '1', color_number: 'C20' )
Color.create( color_name: 'ミドルストーン', color_code: 'B39242', maker_id: '1', color_number: 'C21' )
Color.create( color_name: 'ダークアース', color_code: '504A3D', maker_id: '1', color_number: 'C22' )
Color.create( color_name: 'ダークグリーン(2)', color_code: '405D48', maker_id: '1', color_number: 'C23' )
Color.create( color_name: 'ダークシーグレー', color_code: '727A5E', maker_id: '1', color_number: 'C25' )

Color.create( color_name: 'ダックエッググリーン', color_code: 'D6E0AC', maker_id: '1', color_number: 'C26' )
Color.create( color_name: '機体内部色', color_code: 'B7A836', maker_id: '1', color_number: 'C27' )
Color.create( color_name: '黒鉄色', color_code: '231714', maker_id: '1', color_number: 'C28' )
Color.create( color_name: '艦艇色', color_code: '552E35', maker_id: '1', color_number: 'C29' )
Color.create( color_name: '軍艦色(1)', color_code: '909694', maker_id: '1', color_number: 'C31' )
Color.create( color_name: '軍艦色(2)', color_code: '39555A', maker_id: '1', color_number: 'C32' )
Color.create( color_name: 'つや消しブラック', color_code: '231714', maker_id: '1', color_number: 'C33' )
Color.create( color_name: 'スカイブルー', color_code: '308CD6', maker_id: '1', color_number: 'C34' )
Color.create( color_name: '明灰白色(三菱系)', color_code: 'A6BBC7', maker_id: '1', color_number: 'C35' )
Color.create( color_name: 'RLM74グレーグリーン', color_code: '153D3E', maker_id: '1', color_number: 'C36' )
Color.create( color_name: 'RLM75グレーバイオレット', color_code: '475D56', maker_id: '1', color_number: 'C37' )

Color.create( color_name: 'オリーブドラブ(2)', color_code: '314836', maker_id: '1', color_number: 'C38' )
Color.create( color_name: 'ダークイエロー(サンディイエロー)', color_code: 'BF9D5A', maker_id: '1', color_number: 'C39' )
Color.create( color_name: 'ジャーマングレー(フィールドグレー(1))', color_code: '143C41', maker_id: '1', color_number: 'C40' )
Color.create( color_name: 'レッドブラウン', color_code: '4A2F32', maker_id: '1', color_number: 'C41' )
Color.create( color_name: 'マホガニー', color_code: '3B2F33', maker_id: '1', color_number: 'C42' )
Color.create( color_name: 'ウッドブラウン', color_code: '6A4A31', maker_id: '1', color_number: 'C43' )
Color.create( color_name: 'タン', color_code: 'CAA965', maker_id: '1', color_number: 'C44' )
Color.create( color_name: 'セールカラー', color_code: 'BFB780', maker_id: '1', color_number: 'C45' )
Color.create( color_name: 'クリアーレッド', color_code: 'E73631', maker_id: '1', color_number: '47' )
Color.create( color_name: 'クリアーイエロー', color_code: 'FCD94B', maker_id: '1', color_number: 'C48' )
Color.create( color_name: 'クリアーオレンジ', color_code: 'EB6235', maker_id: '1', color_number: 'C49' )

Color.create( color_name: 'クリアーブルー', color_code: '3AA1E9', maker_id: '1', color_number: 'C50' )
Color.create( color_name: '薄茶色', color_code: 'E6B378', maker_id: '1', color_number: 'C51' )
Color.create( color_name: 'フィールドグレー(2)', color_code: '2A4E49', maker_id: '1', color_number: 'C52' )
Color.create( color_name: 'カーキグリーン', color_code: '204239', maker_id: '1', color_number: 'C54' )
Color.create( color_name: 'カーキ', color_code: '4D5035', maker_id: '1', color_number: 'C55' )
Color.create( color_name: '明灰緑色(中島系)', color_code: '70A19A', maker_id: '1', color_number: 'C56' )
Color.create( color_name: '青竹色', color_code: '30766B', maker_id: '1', color_number: 'C57' )
Color.create( color_name: '黄橙色', color_code: 'ED7839', maker_id: '1', color_number: 'C58' )
Color.create( color_name: 'オレンジ(橙)', color_code: 'E83731', maker_id: '1', color_number: 'C59' )
Color.create( color_name: 'RLM02グレー', color_code: '9F9D89', maker_id: '1', color_number: 'C60' )
Color.create( color_name: '焼鉄色', color_code: '4C5053', maker_id: '1', color_number: 'C61' )
Color.create( color_name: 'つや消しホワイト', color_code: 'FFFFFF', maker_id: '1', color_number: 'C62' )

Color.create( color_name: 'ピンク(桃)', color_code: 'EB6D94', maker_id: '1', color_number: 'C63' )
Color.create( color_name: 'ルマングリーン(黄緑)', color_code: '4AA33D', maker_id: '1', color_number: 'C64' )
Color.create( color_name: 'インディブルー', color_code: '004098', maker_id: '1', color_number: 'C65' )
Color.create( color_name: 'デイトナグリーン', color_code: '459A45', maker_id: '1', color_number: 'C66' )
Color.create( color_name: 'パープル', color_code: '3C2280', maker_id: '1', color_number: 'C67' )
Color.create( color_name: 'モンザレッド', color_code: 'D9322E', maker_id: '1', color_number: 'C68' )
Color.create( color_name: 'グランプリホワイト', color_code: 'F9F8F4', maker_id: '1', color_number: 'C69' )
Color.create( color_name: 'ダークグリーン', color_code: '204239', maker_id: '1', color_number: 'C70' )
Color.create( color_name: 'ミッドナイトブルー', color_code: '1E4247', maker_id: '1', color_number: 'C71' )
Color.create( color_name: 'ミディアムブルー', color_code: '1B4D59', maker_id: '1', color_number: 'C72' )
Color.create( color_name: 'エアクラフトグレー', color_code: '729A96', maker_id: '1', color_number: 'C73' )
Color.create( color_name: 'エアスペリオリティーブルー', color_code: '2A6D79', maker_id: '1', color_number: 'C74' )

Color.create( color_name: 'メタリックレッド', color_code: 'B02724', maker_id: '1', color_number: 'C75' )
Color.create( color_name: 'メタリックブルー', color_code: '0A4EA2', maker_id: '1', color_number: 'C76' )
Color.create( color_name: 'メタリックグリーン', color_code: '3C8950', maker_id: '1', color_number: 'C77' )
Color.create( color_name: 'メタルブラック', color_code: '231714', maker_id: '1', color_number: 'C78' )
Color.create( color_name: 'シャインレッド', color_code: 'E73631', maker_id: '1', color_number: 'C79' )
Color.create( color_name: 'コバルトブルー', color_code: '1E2388', maker_id: '1', color_number: 'C80' )
Color.create( color_name: 'あずき色(赤2号)', color_code: '772931', maker_id: '1', color_number: 'C81' )
Color.create( color_name: 'シャインシルバー', color_code: 'D3D3D4', maker_id: '1', color_number: 'C90' )
Color.create( color_name: 'セミグロスブラック', color_code: '231714', maker_id: '1', color_number: 'C92' )
Color.create( color_name: '灰色9号', color_code: 'B2BEB2', maker_id: '1', color_number: 'C97' )
Color.create( color_name: 'マルーン', color_code: 'AF2832', maker_id: '1', color_number: 'C100' )
Color.create( color_name: 'スモークグレー', color_code: '3D3126', maker_id: '1', color_number: 'C101' )

Color.create( color_name: 'ガンクローム', color_code: 'B1BEC4', maker_id: '1', color_number: 'C104' )
Color.create( color_name: 'キャラクターホワイト', color_code: 'F5F6F4', maker_id: '1', color_number: 'C107' )
Color.create( color_name: 'キャラクターレッド', color_code: 'C82E29', maker_id: '1', color_number: 'C108' )
Color.create( color_name: 'キャラクターイエロー', color_code: 'F0843B', maker_id: '1', color_number: 'C109' )
Color.create( color_name: 'キャラクターブルー', color_code: '004098', maker_id: '1', color_number: 'C110' )
Color.create( color_name: 'キャラクターフレッシュ(1)', color_code: 'FBE4D6', maker_id: '1', color_number: 'C111' )
Color.create( color_name: 'キャラクターフレッシュ(2)', color_code: 'F6BCB8', maker_id: '1', color_number: 'C112' )
Color.create( color_name: 'RLM04イエロー', color_code: 'F5AC41', maker_id: '1', color_number: 'C113' )
Color.create( color_name: 'RLM23レッド', color_code: 'C9303F', maker_id: '1', color_number: 'C114' )
Color.create( color_name: 'RLM65ライトブルー', color_code: '779AA8', maker_id: '1', color_number: 'C115' )
Color.create( color_name: 'RLM66ブラックグレー', color_code: '373434', maker_id: '1', color_number: 'C116' )
Color.create( color_name: 'RLM76ライトブルー', color_code: 'BFD5D4', maker_id: '1', color_number: 'C117' )

Color.create( color_name: 'RLM78ライトブルー', color_code: '80A6B6', maker_id: '1', color_number: 'C118' )
Color.create( color_name: 'RLM79サンドイエロー', color_code: '937055', maker_id: '1', color_number: 'C119' )
Color.create( color_name: 'RLM80オリーブグリーン', color_code: '173E2C', maker_id: '1', color_number: 'C120' )
Color.create( color_name: 'RLM81ブラウンバイオレット', color_code: '595A4E', maker_id: '1', color_number: 'C121' )
Color.create( color_name: 'RLM82ライトグリーン', color_code: '5B8252', maker_id: '1', color_number: 'C122' )
Color.create( color_name: 'RLM83ダークグリーン', color_code: '25554B', maker_id: '1', color_number: 'C123' )
Color.create( color_name: '暗緑色(三菱系)', color_code: '1F4D20', maker_id: '1', color_number: 'C124' )
Color.create( color_name: 'カウリング色', color_code: '000000', maker_id: '1', color_number: 'C125' )
Color.create( color_name: 'コクピット色(三菱系)', color_code: '456340', maker_id: '1', color_number: 'C126' )
Color.create( color_name: 'コクピット色(中島系)', color_code: 'A9B779', maker_id: '1', color_number: 'C127' )
Color.create( color_name: '灰緑色', color_code: 'B1B5A7', maker_id: '1', color_number: 'C128' )
Color.create( color_name: '濃緑色(中島系)', color_code: '45644D', maker_id: '1', color_number: 'C129' )

Color.create( color_name: '濃緑色(川崎系)', color_code: '495D40', maker_id: '1', color_number: 'C130' )
Color.create( color_name: '赤褐色', color_code: '501C11', maker_id: '1', color_number: 'C131' )
Color.create( color_name: '土草色', color_code: '685A32', maker_id: '1', color_number: 'C132' )
Color.create( color_name: 'ロシアングリーン(1)', color_code: '42944B', maker_id: '1', color_number: 'C135' )
Color.create( color_name: 'ロシアングリーン(2)', color_code: '245942', maker_id: '1', color_number: 'C136' )
Color.create( color_name: 'タイヤブラック', color_code: '000000', maker_id: '1', color_number: 'C137' )
Color.create( color_name: 'クリアーグリーン', color_code: '459A45', maker_id: '1', color_number: 'C138' )
Color.create( color_name: 'ホワイトパール', color_code: 'FFFFFF', maker_id: '1', color_number: 'C151' )
Color.create( color_name: 'スーパーホワイト', color_code: 'FFFFFF', maker_id: '1', color_number: 'C156' )
Color.create( color_name: 'スーパーイタリアンレッド', color_code: 'D7322D', maker_id: '1', color_number: 'C158' )
Color.create( color_name: 'スーパーシルバー', color_code: 'DCDDDD', maker_id: '1', color_number: 'C159' )
Color.create( color_name: '蛍光レッド', color_code: 'E73631', maker_id: '1', color_number: 'C171' )

Color.create( color_name: '蛍光イエロー', color_code: 'FFF150', maker_id: '1', color_number: 'C172' )
Color.create( color_name: '蛍光オレンジ', color_code: 'E83731', maker_id: '1', color_number: 'C173' )
Color.create( color_name: '蛍光ピンク', color_code: 'E63B6B', maker_id: '1', color_number: 'C174' )
Color.create( color_name: '蛍光グリーン', color_code: '459A45', maker_id: '1', color_number: 'C175' )
Color.create( color_name: 'グレーFS36081', color_code: '243B45', maker_id: '1', color_number: 'C301' )
Color.create( color_name: 'グリーンFS34092', color_code: '255450', maker_id: '1', color_number: 'C302' )
Color.create( color_name: 'グリーンFS34102', color_code: '475D51', maker_id: '1', color_number: 'C303' )

Color.create( color_name: 'オリーブドラブFS34087', color_code: '373C35', maker_id: '1', color_number: 'C304' )
Color.create( color_name: 'グレーFS36118', color_code: '406B68', maker_id: '1', color_number: 'C305' )
Color.create( color_name: 'グレーFS36270', color_code: '688887', maker_id: '1', color_number: 'C306' )
Color.create( color_name: 'グレーFS36320', color_code: '67888F', maker_id: '1', color_number: 'C307' )
Color.create( color_name: 'グレーFS36375', color_code: '819E9F', maker_id: '1', color_number: 'C308' )
Color.create( color_name: 'グリーンFS34079', color_code: '255450', maker_id: '1', color_number: 'C309' )
Color.create( color_name: 'ブラウンFS30219', color_code: '72624E', maker_id: '1', color_number: 'C310' )
Color.create( color_name: 'グレーFS36622', color_code: 'EAEBD5', maker_id: '1', color_number: 'C311' )
Color.create( color_name: 'グリーンFS34227', color_code: '39845D', maker_id: '1', color_number: 'C312' )
Color.create( color_name: 'イエローFS33531', color_code: 'E8C589', maker_id: '1', color_number: 'C313' )
Color.create( color_name: 'ブルーFS35622', color_code: 'EBF4EB', maker_id: '1', color_number: 'C314' )
Color.create( color_name: 'グレーFS16440', color_code: '99ADA4', maker_id: '1', color_number: 'C315' )

Color.create( color_name: 'ホワイトFS17875', color_code: 'FFFFFF', maker_id: '1', color_number: 'C316' )
Color.create( color_name: 'グレーFS36231', color_code: '6D786A', maker_id: '1', color_number: 'C317' )
Color.create( color_name: 'レドーム', color_code: 'FAD68C', maker_id: '1', color_number: 'C318' )
Color.create( color_name: '薄松葉色', color_code: '2D6D59', maker_id: '1', color_number: 'C319' )
Color.create( color_name: '濃松葉色', color_code: '3A5545', maker_id: '1', color_number: 'C320' )
Color.create( color_name: '黄土色', color_code: 'B4926A', maker_id: '1', color_number: 'C321' )
Color.create( color_name: 'フタロシアニンブルー', color_code: '173551', maker_id: '1', color_number: 'C322' )
Color.create( color_name: 'ライトブルー', color_code: '44B1EC', maker_id: '1', color_number: 'C323' )
Color.create( color_name: 'ライトグレー', color_code: '8CA9A3', maker_id: '1', color_number: 'C324' )
Color.create( color_name: 'グレーFS26440', color_code: 'A6B1A4', maker_id: '1', color_number: 'C325' )
Color.create( color_name: 'ブルーFS15044', color_code: '1E3046', maker_id: '1', color_number: 'C326' )
Color.create( color_name: 'レッドFS11136', color_code: '9E2428', maker_id: '1', color_number: 'C327' )

Color.create( color_name: 'ブルーFS15050', color_code: '173551', maker_id: '1', color_number: 'C328' )
Color.create( color_name: 'イエローFS13538', color_code: 'F4A240', maker_id: '1', color_number: 'C329' )
Color.create( color_name: 'ダークグリーンBS381C/641', color_code: '2E4848', maker_id: '1', color_number: 'C330' )
Color.create( color_name: 'ダークシーグレーBS381C/638', color_code: '4A575A', maker_id: '1', color_number: 'C331' )
Color.create( color_name: 'ライトエアクラフトグレー', color_code: '9CA397', maker_id: '1', color_number: 'C332' )
Color.create( color_name: 'エクストラダークシーグレーBS381C/640', color_code: '1A4752', maker_id: '1', color_number: 'C333' )
Color.create( color_name: 'バリーグレーBS4800/18B21', color_code: '829693', maker_id: '1', color_number: 'C334' )
Color.create( color_name: 'ミディアムシーグレーBS381C/637', color_code: '5E7678', maker_id: '1', color_number: 'C335' )
Color.create( color_name: 'ヘンプBS4800/10B21', color_code: '688E6B', maker_id: '1', color_number: 'C336' )
Color.create( color_name: 'グレイッシュブルーFS35237', color_code: '317179', maker_id: '1', color_number: 'C337' )
Color.create( color_name: 'ライトグレーFS36495', color_code: 'BDC3C4', maker_id: '1', color_number: 'C338' )
Color.create( color_name: 'エンジングレーFS16081', color_code: '1A4752', maker_id: '1', color_number: 'C339' )
Color.create( color_name: 'フィールドグリーンFS34097', color_code: '26553C', maker_id: '1', color_number: 'C340' )

#GaiaNotes Colors
Color.create( color_name: 'ピュアホワイト', color_code: 'FFFFFF', maker_id: '2', color_number: '001' )
Color.create( color_name: 'ピュアブラック', color_code: '000000', maker_id: '2', color_number: '002' )
Color.create( color_name: 'ブライトレッド', color_code: 'FF0000', maker_id: '2', color_number: '003' )
Color.create( color_name: 'ウルトラブルー', color_code: '144EA2', maker_id: '2', color_number: '004' )
Color.create( color_name: 'サンシャインイエロー', color_code: 'FFFF00', maker_id: '2', color_number: '005' )
Color.create( color_name: 'ブラットベース', color_code: 'E0E0E0', maker_id: '2', color_number: '006' )
Color.create( color_name: 'ブライトシルバー', color_code: '727A7D', maker_id: '2', color_number: '009' )
Color.create( color_name: 'ブライトゴールド', color_code: '905C20', maker_id: '2', color_number: '041' )

Color.create( color_name: 'フラットホワイト', color_code: 'FFFFFF', maker_id: '2', color_number: '011' )
Color.create( color_name: 'フラットブラック', color_code: '000000', maker_id: '2', color_number: '012' )
Color.create( color_name: 'ビリジアングリーン', color_code: '337A65', maker_id: '2', color_number: '013' )
Color.create( color_name: 'ナチュラルブラウン', color_code: '9E221E', maker_id: '2', color_number: '014' )
Color.create( color_name: 'ピュアオレンジ', color_code: 'ED3833', maker_id: '2', color_number: '015' )
Color.create( color_name: 'ブリリアントピンク', color_code: 'EE5D85', maker_id: '2', color_number: '016' )
Color.create( color_name: 'パープルヴァイオレット', color_code: '4B45BF', maker_id: '2', color_number: '017' )
Color.create( color_name: 'エメラルドグリーン', color_code: '6AE795', maker_id: '2', color_number: '018' )
Color.create( color_name: 'ラベンダー', color_code: 'D8CCF4', maker_id: '2', color_number: '019' )
Color.create( color_name: 'ガンメタル', color_code: '0B0B0B', maker_id: '2', color_number: '020' )

Color.create( color_name: 'セミグロスホワイト', color_code: 'FFFFFF', maker_id: '2', color_number: '021' )
Color.create( color_name: 'セミグロスブラック', color_code: '4E4D52', maker_id: '2', color_number: '022' )
Color.create( color_name: 'スカーレット', color_code: 'EB3732', maker_id: '2', color_number: '023' )
Color.create( color_name: 'コバルトブルー', color_code: '356BF1', maker_id: '2', color_number: '024' )
Color.create( color_name: '橙黄色', color_code: 'F28A3C', maker_id: '2', color_number: '025' )
Color.create( color_name: 'ライトグリーン', color_code: '93A267', maker_id: '2', color_number: '026' )
Color.create( color_name: 'ダークグリーン', color_code: '1F291E', maker_id: '2', color_number: '027' )
Color.create( color_name: 'ストーングリーン', color_code: '4FB7AE', maker_id: '2', color_number: '028' )

Color.create( color_name: 'アルティメットホワイト', color_code: 'FFFFFF', maker_id: '2', color_number: '031' )
Color.create( color_name: 'アルティメットブラック', color_code: '000000', maker_id: '2', color_number: '032' )
Color.create( color_name: '純色シアン', color_code: '102EAD', maker_id: '2', color_number: '033' )
Color.create( color_name: '純色マゼンタ', color_code: '4D0C10', maker_id: '2', color_number: '034' )
Color.create( color_name: '純色イエロー', color_code: 'F7B643', maker_id: '2', color_number: '035' )
Color.create( color_name: '純色グリーン', color_code: '2E5C58', maker_id: '2', color_number: '036' )
Color.create( color_name: '純色バイオレット', color_code: '403960', maker_id: '2', color_number: '037' )

Color.create( color_name: 'クリアーレッド', color_code: 'BE2C31', maker_id: '2', color_number: '041' )
Color.create( color_name: 'クリアーオレンジ', color_code: 'D1302B', maker_id: '2', color_number: '042' )
Color.create( color_name: 'クリアーブラック', color_code: '3C403B', maker_id: '2', color_number: '043' )
Color.create( color_name: 'クリアーブルー', color_code: '0143C3', maker_id: '2', color_number: '044' )
Color.create( color_name: 'クリアーイエロー', color_code: 'FFF050', maker_id: '2', color_number: '045' )
Color.create( color_name: 'クリアーブラウン', color_code: '6C2A2B', maker_id: '2', color_number: '046' )
Color.create( color_name: 'クリアーパープル', color_code: '6F42DD', maker_id: '2', color_number: '047' )
Color.create( color_name: 'クリアーグリーン', color_code: '55B72D', maker_id: '2', color_number: '048' )
Color.create( color_name: 'クリアーピンク', color_code: 'EC449B', maker_id: '2', color_number: '049' )
Color.create( color_name: 'クリアーホワイト', color_code: 'F3F3F3', maker_id: '2', color_number: '050' )

Color.create( color_name: 'ノーツフレッシュ', color_code: 'F7E5CF', maker_id: '2', color_number: '051' )
Color.create( color_name: 'ノーツフレッシュ ホワイト', color_code: 'EADED2', maker_id: '2', color_number: '051' )
Color.create( color_name: 'ノーツフレッシュ ピンク', color_code: 'F3A69C', maker_id: '2', color_number: '051' )
Color.create( color_name: 'ノーツフレッシュ オレンジ', color_code: 'E7B78F', maker_id: '2', color_number: '051' )
Color.create( color_name: 'サフレスフレッシュピンク', color_code: 'F3A19B', maker_id: '2', color_number: '059' )
Color.create( color_name: 'サフレスフレッシュオレンジ', color_code: 'FEE879', maker_id: '2', color_number: '060' )

Color.create( color_name: 'ミッドナイトブルー', color_code: '222029', maker_id: '2', color_number: '061' )
Color.create( color_name: 'ミディアムブルー', color_code: '41637F', maker_id: '2', color_number: '061' )
Color.create( color_name: 'ブルーグレー', color_code: '44696D', maker_id: '2', color_number: '061' )

Color.create( color_name: 'ニュートラルグレーⅠ', color_code: 'CECECE', maker_id: '2', color_number: '071' )
Color.create( color_name: 'ニュートラルグレーⅡ', color_code: 'B4B4B4', maker_id: '2', color_number: '071' )
Color.create( color_name: 'ニュートラルグレーⅢ', color_code: '8E8E8E', maker_id: '2', color_number: '071' )
Color.create( color_name: 'ニュートラルグレーⅣ', color_code: '6C6C6C', maker_id: '2', color_number: '071' )
Color.create( color_name: 'ニュートラルグレーⅤ', color_code: '4E4E4E', maker_id: '2', color_number: '071' )

Color.create( color_name: '蛍光ブルー', color_code: '0837C9', maker_id: '2', color_number: '101' )
Color.create( color_name: '蛍光ピンク', color_code: 'ED3A52', maker_id: '2', color_number: '102' )
Color.create( color_name: '蛍光レッド', color_code: 'ED3833', maker_id: '2', color_number: '103' )
Color.create( color_name: '蛍光グリーン', color_code: '63D44F', maker_id: '2', color_number: '104' )
Color.create( color_name: '蛍光イエロー', color_code: 'E9F74E', maker_id: '2', color_number: '105' )
Color.create( color_name: '蛍光オレンジ', color_code: 'ED3833', maker_id: '2', color_number: '106' )
Color.create( color_name: '蛍光イエローグリーン', color_code: '73F340', maker_id: '2', color_number: '107' )
Color.create( color_name: '蛍光ブルーグリーン', color_code: '49AFB7', maker_id: '2', color_number: '108' )

Color.create( color_name: 'スターブライトシルバー', color_code: 'BBBBBB', maker_id: '2', color_number: '121' )
Color.create( color_name: 'スターブライトゴールド', color_code: 'B48334', maker_id: '2', color_number: '122' )
Color.create( color_name: 'スターブライトジュラルミン', color_code: '67675E', maker_id: '2', color_number: '123' )
Color.create( color_name: 'スターブライトブラス', color_code: 'A5852C', maker_id: '2', color_number: '124' )
Color.create( color_name: 'スターブライトアイアン', color_code: '5F5F5F', maker_id: '2', color_number: '125' )

Color.create( color_name: 'パールシルバー', color_code: 'E2DFDA', maker_id: '2', color_number: '131' )
Color.create( color_name: 'パールゴールド', color_code: 'C47C34', maker_id: '2', color_number: '132' )
Color.create( color_name: 'パールカッパー', color_code: 'BE6F44', maker_id: '2', color_number: '133' )
Color.create( color_name: 'プリズム パープルグリーン', color_code: 'B0C09C', maker_id: '2', color_number: '134' )
Color.create( color_name: 'プリズム ブルーグリーン', color_code: 'C4D9D4', maker_id: '2', color_number: '135' )
Color.create( color_name: 'プリズム マゼンタゴールド', color_code: 'CD542D', maker_id: '2', color_number: '136' )

Color.create( color_name: 'ダークイエロー1', color_code: 'B69D4C', maker_id: '2', color_number: '201' )
Color.create( color_name: 'オリーブグリーン', color_code: '485F42', maker_id: '2', color_number: '202' )
Color.create( color_name: 'レッドブラウン', color_code: '3A2023', maker_id: '2', color_number: '203' )
Color.create( color_name: 'ダークイエロー2', color_code: 'C1AC7A', maker_id: '2', color_number: '204' )
Color.create( color_name: 'ゲルプブラウン', color_code: 'AC8542', maker_id: '2', color_number: '205' )
Color.create( color_name: 'グラウグリュン', color_code: '8B693A', maker_id: '2', color_number: '206' )
Color.create( color_name: 'ブラウン', color_code: 'CD9D69', maker_id: '2', color_number: '207' )
Color.create( color_name: 'グラウ', color_code: 'CAB793', maker_id: '2', color_number: '208' )

Color.create( color_name: '灰緑色', color_code: 'C4C392', maker_id: '2', color_number: '211' )
Color.create( color_name: '緑色', color_code: '324133', maker_id: '2', color_number: '212' )
Color.create( color_name: '灰緑色', color_code: 'CDCFB4', maker_id: '2', color_number: '213' )
Color.create( color_name: '暗緑色', color_code: '225539', maker_id: '2', color_number: '214' )
Color.create( color_name: 'FS34079 ダークグリーン', color_code: '3E3D21', maker_id: '2', color_number: '215' )
Color.create( color_name: 'FS34102 グリーン', color_code: '474E12', maker_id: '2', color_number: '216' )
Color.create( color_name: 'FS30219 タン', color_code: '876D48', maker_id: '2', color_number: '217' )
Color.create( color_name: 'FS36622 グレー', color_code: 'BEBB9C', maker_id: '2', color_number: '218' )
Color.create( color_name: 'FS36440 ライトガルグレー', color_code: '999884', maker_id: '2', color_number: '219' )

Color.create( color_name: 'ジャーマングレー', color_code: '28282B', maker_id: '2', color_number: '221' )
Color.create( color_name: 'オキサイドレッド', color_code: '9A3E31', maker_id: '2', color_number: '222' )
Color.create( color_name: 'インテリアカラー', color_code: 'ECDEBD', maker_id: '2', color_number: '223' )


#Tamiya Colors
# Color.create( color_name: 'ブラック', color_code: '', maker_id: '3', color_number: 'LP01' )
# Color.create( color_name: 'ホワイト', color_code: '', maker_id: '3', color_number: 'LP02' )
# Color.create( color_name: 'フラットブラック', color_code: '', maker_id: '3', color_number: 'LP03' )
# Color.create( color_name: 'フラットホワイト', color_code: '', maker_id: '3', color_number: 'LP04' )
# Color.create( color_name: 'セミグロスブラック', color_code: '', maker_id: '3', color_number: 'LP05' )
# Color.create( color_name: 'ピュアブルー', color_code: '', maker_id: '3', color_number: 'LP06' )
# Color.create( color_name: 'ピュアレッド', color_code: '', maker_id: '3', color_number: 'LP07' )
# Color.create( color_name: 'ピュアイエロー', color_code: '', maker_id: '3', color_number: 'LP08' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP09' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP10' )
# Color.create( color_name: 'シルバー', color_code: '', maker_id: '3', color_number: 'LP11' )
# Color.create( color_name: '呉海軍工廠グレイ', color_code: '', maker_id: '3', color_number: 'LP12' )
# Color.create( color_name: '佐世保海軍工廠グレイ', color_code: '', maker_id: '3', color_number: 'LP13' )
# Color.create( color_name: '舞鶴海軍工廠グレイ', color_code: '', maker_id: '3', color_number: 'LP14' )
# Color.create( color_name: '横須賀海軍工廠グレイ', color_code: '', maker_id: '3', color_number: 'LP15' )
# Color.create( color_name: '木甲板色', color_code: '', maker_id: '3', color_number: 'LP16' )
# Color.create( color_name: 'リノリウム甲板色', color_code: '', maker_id: '3', color_number: 'LP17' )
# Color.create( color_name: 'ダルレッド', color_code: '', maker_id: '3', color_number: 'LP18' )
# Color.create( color_name: 'ガンメタル', color_code: '', maker_id: '3', color_number: 'LP19' )
# Color.create( color_name: 'ライトガンメタル', color_code: '', maker_id: '3', color_number: 'LP20' )

# Color.create( color_name: 'イタリアンレッド', color_code: '', maker_id: '3', color_number: 'LP21' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP22' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP23' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP24' )
# Color.create( color_name: '茶色(陸上自衛隊)', color_code: '', maker_id: '3', color_number: 'LP25' )
# Color.create( color_name: '濃緑色(陸上自衛隊)', color_code: '', maker_id: '3', color_number: 'LP26' )
# Color.create( color_name: 'ジャーマングレー', color_code: '', maker_id: '3', color_number: 'LP27' )
# Color.create( color_name: 'オリーブドラブ', color_code: '', maker_id: '3', color_number: 'LP28' )
# Color.create( color_name: 'オリーブドラブ2', color_code: '', maker_id: '3', color_number: 'LP29' )
# Color.create( color_name: 'ライトサンド', color_code: '', maker_id: '3', color_number: 'LP30' )
# Color.create( color_name: '暗緑色2(日本海軍)', color_code: '', maker_id: '3', color_number: 'LP31' )
# Color.create( color_name: '明灰白色(日本海軍)', color_code: '', maker_id: '3', color_number: 'LP32' )
# Color.create( color_name: '灰緑色(日本海軍)', color_code: '', maker_id: '3', color_number: 'LP33' )
# Color.create( color_name: 'ライトグレイ', color_code: '', maker_id: '3', color_number: 'LP34' )
# Color.create( color_name: 'インシグニアホワイト', color_code: '', maker_id: '3', color_number: 'LP35' )
# Color.create( color_name: 'ダークゴーストグレイ', color_code: '', maker_id: '3', color_number: 'LP36' )
# Color.create( color_name: 'ライトゴーストグレイ', color_code: '', maker_id: '3', color_number: 'LP37' )
# Color.create( color_name: 'フラットアルミ', color_code: '', maker_id: '3', color_number: 'LP38' )
# Color.create( color_name: 'レーシングホワイト', color_code: '', maker_id: '3', color_number: 'LP39' )
# Color.create( color_name: 'メタリックブラック', color_code: '', maker_id: '3', color_number: 'LP40' )

# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP41' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP42' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP43' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP44' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP45' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP46' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP47' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP48' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP49' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP50' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP51' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP52' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP53' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP54' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP55' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP56' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP57' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP58' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP59' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP60' )

# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP61' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP62' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP63' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP64' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP65' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP66' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP67' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP68' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP69' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP70' )

# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP71' )
# Color.create( color_name: '', color_code: '', maker_id: '3', color_number: 'LP72' )